export const LacesTypes = {
  LOAD_REQUEST: "@laces/LOAD_REQUEST",
  LOAD_SUCCESS: "@laces/LOAD_SUCCESS",
  LOAD_FAILURE: "@laces/LOAD_FAILURE",
  CREATE_REQUEST: "@laces/CREATE_REQUEST",
  CREATE_FAILURE: "@laces/CREATE_FAILURE",
  CREATE_SUCCESS: "@laces/CREATE_SUCCESS"
};
